import NextAuth from 'next-auth'
import GitHub from 'next-auth/providers/github'
import Credentials from 'next-auth/providers/credentials'
import { db, schema } from '@/lib/db/client'
import { eq } from 'drizzle-orm'
import { consumeMagicToken } from '@/lib/auth/magic'

type MarinaTokenFields = {
  accessToken?: string
  appUserId?: number
  login?: string
}

type GhProfile = {
  id: number
  login: string
  name?: string
  email?: string
  avatar_url?: string
}

export const { handlers, auth, signIn, signOut } = NextAuth({
  // NextAuth v5 enforces a strict origin check by default and throws
  // `UntrustedHost` when run behind any reverse proxy / on production-style
  // hosts (incl. `pnpm start`). Trust the host header — production deployments
  // should additionally set AUTH_URL so callback URLs are computed correctly.
  trustHost: true,
  providers: [
    GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
      authorization: { params: { scope: 'read:user user:email repo' } },
    }),
    // Email magic-link via Credentials. The "credential" is the one-time token
    // generated by /api/auth/magic/start. We consume it (single-use) here and
    // upsert a user keyed on email. This avoids the full NextAuth Email
    // provider's adapter requirement while giving the same UX.
    Credentials({
      id: 'magic',
      name: 'Email magic link',
      credentials: {
        token: { label: 'Token', type: 'text' },
      },
      async authorize(credentials) {
        const token = (credentials?.token as string | undefined)?.trim()
        if (!token) return null
        const email = await consumeMagicToken(token)
        if (!email) return null

        // Upsert user by email.
        let user = await db.query.users.findFirst({ where: eq(schema.users.email, email) })
        if (!user) {
          const login = email.split('@')[0]!.slice(0, 39)
          const [created] = await db
            .insert(schema.users)
            .values({
              email,
              login,
              name: null,
            })
            .returning()
          user = created
        }
        return {
          id: String(user.id),
          email: user.email,
          name: user.name ?? null,
          image: user.image ?? user.avatarUrl ?? null,
        }
      },
    }),
  ],
  session: { strategy: 'jwt' },
  callbacks: {
    async jwt({ token, account, profile, user }) {
      const t = token as typeof token & MarinaTokenFields

      // GitHub sign-in path
      if (account?.provider === 'github' && account?.access_token && profile) {
        const ghProfile = profile as unknown as GhProfile
        const existing = await db.query.users.findFirst({
          where: eq(schema.users.githubId, ghProfile.id),
        })
        const row = existing
          ? (
              await db
                .update(schema.users)
                .set({
                  login: ghProfile.login,
                  name: ghProfile.name ?? existing.name,
                  email: ghProfile.email ?? existing.email,
                  avatarUrl: ghProfile.avatar_url ?? existing.avatarUrl,
                  accessToken: account.access_token,
                })
                .where(eq(schema.users.id, existing.id))
                .returning()
            )[0]
          : (
              await db
                .insert(schema.users)
                .values({
                  githubId: ghProfile.id,
                  login: ghProfile.login,
                  name: ghProfile.name,
                  email: ghProfile.email,
                  avatarUrl: ghProfile.avatar_url,
                  accessToken: account.access_token,
                })
                .returning()
            )[0]
        t.appUserId = row.id
        t.login = row.login
        t.accessToken = account.access_token
      }

      // Magic-link path: `user.id` is the numeric DB id (as a string per NextAuth).
      if (account?.provider === 'magic' && user?.id) {
        const numericId = Number(user.id)
        if (Number.isFinite(numericId)) {
          const row = await db.query.users.findFirst({ where: eq(schema.users.id, numericId) })
          if (row) {
            t.appUserId = row.id
            t.login = row.login
            t.accessToken = undefined
          }
        }
      }

      return t
    },
    async session({ session, token }) {
      const t = token as typeof token & MarinaTokenFields
      session.accessToken = t.accessToken
      session.appUserId = t.appUserId
      session.login = t.login
      return session
    },
  },
})
