/**
 * Pixel-art character roster (50 avatars).
 *
 * Each character is hand-designed to evoke a well-known icon from comics,
 * anime or fiction WITHOUT using the trademarked name. The pixel
 * silhouette + palette do the recognising; the displayed name is a
 * descriptive, legal-safe phrase ("The Iron Knight", "The Web Crawler",
 * "The Grey Wizard").
 *
 * Why this matters:
 *   - We can't use "Iron Man" / "Spider-Man" / "Naruto" in a paid product
 *     without licensing — but a stylised pixel bust evokes them just fine.
 *   - Teammates get to pick something that resonates with their identity
 *     (heroes, anime, fantasy, detective).
 *   - Per-org uniqueness is still enforced one level up
 *     (`lib/characters/availability.ts`), so two teammates can't both be
 *     The Iron Knight.
 *
 * Each grid is 16x16:
 *   '.'  = transparent
 *   other ASCII char  = a palette entry
 *
 * If you add a character, also add it to the `CharacterKey` union AND to
 * the `REMAP` table in `scripts/migrate-character-keys.ts` if you want
 * existing users with the old key to land on the new one.
 */

export type CharacterKey =
  // Marvel-inspired
  | 'iron_knight'
  | 'web_crawler'
  | 'star_captain'
  | 'thunder_lord'
  | 'behemoth'
  | 'berserker'
  | 'mercenary'
  | 'panther_king'
  | 'sorcerer'
  | 'trickster'
  | 'spy'
  | 'scarlet_hex'
  | 'marksman'
  | 'synthetic'
  | 'shrinker'
  | 'outlaw'
  | 'bandit'
  | 'sapling'
  // DC-inspired
  | 'night_watcher'
  | 'last_son'
  | 'amazon'
  | 'speedster'
  | 'tide_lord'
  | 'ring_bearer'
  | 'jester'
  | 'wild_card'
  | 'acrobat'
  | 'boy_wonder'
  | 'cat_burglar'
  | 'mogul'
  // Anime-inspired
  | 'fox_ninja'
  | 'avenger_ninja'
  | 'copy_ninja'
  | 'shadow_ninja'
  | 'straw_hat'
  | 'three_swords'
  | 'six_eyes'
  | 'captain'
  | 'saiyan'
  | 'prince_warrior'
  // Fiction / fantasy / detective
  | 'chosen'
  | 'brightest'
  | 'loyal'
  | 'grey_wizard'
  | 'returned_king'
  | 'bastard'
  | 'imp'
  | 'detective'
  | 'pirate'
  | 'boogeyman'

export type Character = {
  key: CharacterKey
  name: string
  codename: string
  tagline: string
  /** Primary brand color for accents */
  color: string
  /** Soft glow / aura color used on cards + badges */
  glow: string
  palette: Record<string, string>
  grid: string[]
}

const GRID_SIZE = 16

function check(grid: string[]): string[] {
  if (grid.length !== GRID_SIZE) {
    throw new Error(`grid must be ${GRID_SIZE} rows, got ${grid.length}`)
  }
  grid.forEach((row, i) => {
    if (row.length !== GRID_SIZE) {
      throw new Error(`grid row ${i} must be ${GRID_SIZE} chars: "${row}" (${row.length})`)
    }
  })
  return grid
}

export const CHARACTERS: Character[] = [
  /* ====================== Marvel-inspired ====================== */
  {
    key: 'iron_knight',
    name: 'The Iron Knight',
    codename: 'Armored & airborne',
    tagline: 'Genius, billionaire, ships to prod.',
    color: '#dc2626',
    glow: '#fbbf24',
    palette: { A: '#7f1d1d', B: '#dc2626', C: '#fbbf24', D: '#fffbeb' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBCCCCCCBBA..',
      '..ABCCAAAACCBA..',
      '..ABCCAAAACCBA..',
      '..ABCCCCCCCCBA..',
      '..ABCCCCCCCCBA..',
      '..ABCCCBBCCCBA..',
      '..ABBCCCCCCBBA..',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBCCCCCCBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'web_crawler',
    name: 'The Web Crawler',
    codename: 'Friendly neighborhood reviewer',
    tagline: 'Catches bugs before they ship.',
    color: '#b91c1c',
    glow: '#1d4ed8',
    palette: { A: '#450a0a', B: '#dc2626', C: '#1d4ed8', D: '#ffffff', E: '#000000' },
    grid: check([
      '................',
      '.....AAAAAA.....',
      '....ABBBBBBA....',
      '...ACBBBBBBCA...',
      '..ACBBBBBBBBCA..',
      '..ABDDDABDDDBA..',
      '..ABDEDABDEDBA..',
      '..ABDDDABDDDBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBABBBBBA..',
      '..ABBEEEEEEBBA..',
      '...ABBBBBBBBA...',
      '..CCCBBBBBBCCC..',
      '..CCCBBBBBBCCC..',
      '...CCBBBBBBCC...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'star_captain',
    name: 'The Star Captain',
    codename: 'Holds the line',
    tagline: 'Can do this all day.',
    color: '#1d4ed8',
    glow: '#fde047',
    palette: { A: '#1e3a8a', B: '#2563eb', C: '#ffffff', D: '#dc2626', E: '#1a1a1a' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBCCCCCCBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBCEEBCEEBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBDDBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBCCCCCCBBA..',
      '...ABBBBBBBBA...',
      '..ABBBCCCCBBBA..',
      '..ABBCDDDDCBBA..',
      '..ABBBDDDDBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'thunder_lord',
    name: 'The Thunder Lord',
    codename: 'Always pushing hammers',
    tagline: 'Never to main, only to dev.',
    color: '#94a3b8',
    glow: '#fde047',
    palette: { A: '#1e293b', B: '#94a3b8', C: '#fde047', D: '#fef3c7', E: '#3b82f6', F: '#cbd5e1' },
    grid: check([
      '..BB........BB..',
      '.BAB........BAB.',
      '.BABBBBBBBBBBAB.',
      '..AFFFFFFFFFFFA.',
      '..AFCCCCCCCCFFA.',
      '..AFCDDEEDDCCFA.',
      '..AFCDDEEDDCCFA.',
      '..AFCCCCCCCCCFA.',
      '..AFCCDDDDCCCFA.',
      '..AFCCCCCCCCCFA.',
      '...ABCCCCCCCBA..',
      '..ABBCCCCCCCBBA.',
      '..ABBCCEEEECBBA.',
      '..ABBCCCCCCBBBA.',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'behemoth',
    name: 'The Behemoth',
    codename: 'Smashes blockers',
    tagline: 'Always angry. Always shipping.',
    color: '#15803d',
    glow: '#86efac',
    palette: { A: '#052e16', B: '#16a34a', C: '#22c55e', D: '#ffffff', E: '#1a1a1a' },
    grid: check([
      '................',
      '...AAACCCAAA....',
      '..ACCCCCCCCCA...',
      '..ACBBBBBBBCA...',
      '.ABBBBBBBBBBBA..',
      '.ABBDEBBBBDEBA..',
      '.ABBDEBBBBDEBA..',
      '.ABBBBBBBBBBBA..',
      '.ABBBEEEEEEBBA..',
      '.ABBBEAAAAEBBA..',
      '.ABBBEAEEAEBBA..',
      '..ABBEEEEEEBA...',
      '..ABBBBBBBBBA...',
      '.ABBBCBBBBCBBA..',
      '..BBBBBBBBBB....',
      '....BBBBBB......',
    ]),
  },
  {
    key: 'berserker',
    name: 'The Berserker',
    codename: 'Three claws, ten thousand commits',
    tagline: 'Best at what he does.',
    color: '#facc15',
    glow: '#fef9c3',
    palette: { A: '#1c1917', B: '#facc15', C: '#3b82f6', D: '#ffffff', E: '#000000', F: '#b45309' },
    grid: check([
      '................',
      '..BB........BB..',
      '..BAB......BAB..',
      '..BAAB....BAAB..',
      '..BAAABBBBAAAB..',
      '..BAAAABBAAAAB..',
      '..ABBBBBBBBBBA..',
      '..ABDDBEEBDDBA..',
      '..ABBBBBBBBBBA..',
      '..ABBFFBBFFBBA..',
      '..ABBBFFFFBBBA..',
      '..ABBBBBBBBBBA..',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...AAAAAAAAAA...',
    ]),
  },
  {
    key: 'mercenary',
    name: 'The Mercenary',
    codename: 'Chaotic neutral. Ships anyway.',
    tagline: 'Breaks the fourth wall and the build.',
    color: '#b91c1c',
    glow: '#fca5a5',
    palette: { A: '#1c1917', B: '#dc2626', C: '#7f1d1d', D: '#ffffff', E: '#000000' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABCBBBBBBCBA..',
      '..ABCBBBBBBCBA..',
      '..ABEDDDDDDEBA..',
      '..ABEDDBBDDEBA..',
      '..ABEDDBBDDEBA..',
      '..ABBEEDDEEBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBEEEEBBBA..',
      '..ABBBBBBBBBBA..',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...AAAAAAAAAA...',
    ]),
  },
  {
    key: 'panther_king',
    name: 'The Panther King',
    codename: 'Wakes silent. Deploys quieter.',
    tagline: 'Vibes only, vibranium only.',
    color: '#1e1b4b',
    glow: '#a855f7',
    palette: { A: '#0c0a44', B: '#1e1b4b', C: '#3b0764', D: '#a855f7', E: '#fde047', F: '#000000' },
    grid: check([
      '..AA........AA..',
      '..AAA......AAA..',
      '.AAACC....CCAAA.',
      '.AACCDA..ADCCAA.',
      '.AACCDA..ADCCAA.',
      '.AACCAAAAAACCAA.',
      '.AACCAAAAAACCAA.',
      '.AAAAFFAAFFAAAA.',
      '.AAAAFFAAFFAAAA.',
      '.AAAAAAAAAAAAAA.',
      '.AAAAFFFFFFAAAA.',
      '..AAAFFCCFFAAA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'sorcerer',
    name: 'The Sorcerer',
    codename: 'Bending time, bending TypeScript',
    tagline: '14,000,605 outcomes simulated.',
    color: '#b91c1c',
    glow: '#fbbf24',
    palette: { A: '#7c2d12', B: '#b91c1c', C: '#fbbf24', D: '#0f172a', E: '#fde68a', F: '#9a3412' },
    grid: check([
      '................',
      '.....BBBBBB.....',
      '....BFFFFFFB....',
      '...BFFFFFFFFB...',
      '..BFEEEEEEEEFB..',
      '..BFEDDEEDDEFB..',
      '..BFEEEEEEEEFB..',
      '..BFEECCCCEEFB..',
      '..BFEEEEEEEEFB..',
      '..ABBFEEEEFBBA..',
      '..ABBBCCCCBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...ABBBBBBBBA...',
      '....ABBBBBBA....',
      '.....AAAAAA.....',
    ]),
  },
  {
    key: 'trickster',
    name: 'The Trickster',
    codename: 'Mischief, managed',
    tagline: 'Always has a Plan G.',
    color: '#15803d',
    glow: '#fde047',
    palette: { A: '#052e16', B: '#15803d', C: '#fde047', D: '#fef3c7', E: '#000000', F: '#22c55e' },
    grid: check([
      '..CC........CC..',
      '..ACC......CCA..',
      '..AACC....CCAA..',
      '..AAACCCCCCAAA..',
      '..AABBBBBBBBAA..',
      '..ABDDDDDDDDBA..',
      '..ABDDEEDDEEDBA.',
      '..ABDDEEDDEEDBA.',
      '..ABDDDDDDDDBA..',
      '..ABDDFFFFDDBA..',
      '..ABBDDDDDDBBA..',
      '...ABBBBBBBBA...',
      '..BBBBBBBBBBBB..',
      '..BBCCBBBBCCBB..',
      '..ABBBBBBBBBBA..',
      '...AAAAAAAAAA...',
    ]),
  },
  {
    key: 'spy',
    name: 'The Spy',
    codename: 'Quiet commits, loud results',
    tagline: 'Ledger says: balanced.',
    color: '#9f1239',
    glow: '#fb7185',
    palette: { A: '#1f2937', B: '#7f1d1d', C: '#b91c1c', D: '#fde68a', E: '#0f172a', F: '#fecaca' },
    grid: check([
      '................',
      '.....BBBBBB.....',
      '....BCCCCCCB....',
      '...BCCCCCCCCB...',
      '..BCCFFFFFFCCB..',
      '..BCFFFFFFFFCB..',
      '..BCFEEFFEEFCB..',
      '..BCFFFFFFFFCB..',
      '..BCFFFEEFFFCB..',
      '..BBFFFFFFFFBB..',
      '...ABBBBBBBBA...',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'scarlet_hex',
    name: 'The Scarlet Hex',
    codename: 'Bends reality, by accident',
    tagline: 'Once. Twice. Sometimes more.',
    color: '#9a1a39',
    glow: '#fda4af',
    palette: { A: '#4c0519', B: '#9a1a39', C: '#dc2626', D: '#f5d6b0', E: '#1a1a1a', F: '#fde68a' },
    grid: check([
      '....BBB....BBB..',
      '...BBBB...BBBBB.',
      '..BBBBBBBBBBBBB.',
      '..BBBBBBBBBBBB..',
      '..BDDDDDDDDDDB..',
      '..BDDDDDDDDDDB..',
      '..BDDEEDDEEDDB..',
      '..BDDEEDDEEDDB..',
      '..BDDDDDDDDDDB..',
      '..BBBDDCCDDDBB..',
      '..CCCBBBBBBCCC..',
      '..CCCCCCCCCCCC..',
      '..CCBBBBBBBBCC..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
      '................',
    ]),
  },
  {
    key: 'marksman',
    name: 'The Marksman',
    codename: 'Quiver of well-named PRs',
    tagline: 'Never misses the mark.',
    color: '#581c87',
    glow: '#a855f7',
    palette: { A: '#1e1b4b', B: '#581c87', C: '#a855f7', D: '#fde68a', E: '#000000', F: '#dc2626' },
    grid: check([
      '................',
      '....BBBBBBBB....',
      '...BCCCCCCCCB...',
      '..BCBBBBBBBBCB..',
      '..BCBDDDDDDBCB..',
      '..BCBDEEDDEEBCB.',
      '..BCBDDDDDDBCB..',
      '..BCBDDFFDDBCB..',
      '..BCBBBBBBBBCB..',
      '...BBCCCCCCBB...',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
      '................',
    ]),
  },
  {
    key: 'synthetic',
    name: 'The Synthetic',
    codename: 'Made of mind, made of code',
    tagline: 'A logic gate with feelings.',
    color: '#9333ea',
    glow: '#fde047',
    palette: { A: '#3b0764', B: '#9333ea', C: '#fde047', D: '#fdf4ff', E: '#1a1a1a', F: '#fbbf24' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBBBCCCBBBA..',
      '..ABBBCFFFCBBBA.',
      '..ABBBBCCCBBBBA.',
      '..ABBEEBBBEEBA..',
      '..ABBBBBBBBBBA..',
      '..ABBDDDDDDBBA..',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'shrinker',
    name: 'The Shrinker',
    codename: 'Big problems, small footprint',
    tagline: 'Quantum tunnels for everyone.',
    color: '#dc2626',
    glow: '#7dd3fc',
    palette: { A: '#7f1d1d', B: '#dc2626', C: '#fbbf24', D: '#0ea5e9', E: '#000000', F: '#f1f5f9' },
    grid: check([
      '......AAAA......',
      '....ABBBBBBA....',
      '...ABBCCCCBBA...',
      '..ABBCFFFFCBBA..',
      '..ABCCEEEECCBA..',
      '..ABCCDDDDCCBA..',
      '..ABCCEEEECCBA..',
      '..ABBCCCCCCBBA..',
      '...ABBCDDCBBA...',
      '....ABBBBBBA....',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBDDDDDDBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'outlaw',
    name: 'The Outlaw',
    codename: 'Mixtape ready, ship ready',
    tagline: 'Hooked on a feeling.',
    color: '#7c2d12',
    glow: '#fbbf24',
    palette: { A: '#451a03', B: '#7c2d12', C: '#fbbf24', D: '#1c1917', E: '#dc2626', F: '#e5e7eb' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBCCCCCCBBA..',
      '..ABCFFFFFFCBA..',
      '..ABCFEEEEFFCBA.',
      '..ABCFEDDEEFCBA.',
      '..ABCFFFFFFFCBA.',
      '..ABCFFEEEEFCBA.',
      '..ABBCCCCCCBBA..',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBEEEEEEBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'bandit',
    name: 'The Bandit',
    codename: 'Trash panda, top engineer',
    tagline: 'Builds weapons from spare parts.',
    color: '#78350f',
    glow: '#fde68a',
    palette: { A: '#1c1917', B: '#78350f', C: '#a8a29e', D: '#fde68a', E: '#000000', F: '#dc2626' },
    grid: check([
      '..CC........CC..',
      '.CCAC........CC.',
      '.CCAACC....CCCC.',
      '..CAAACCCCCCAC..',
      '.CCAAAAAAAAAACC.',
      '..CCAAAAAAAACC..',
      '..CCBBBBBBBBCC..',
      '..CBEEBBBBEEBC..',
      '..CBBBBBBBBBBC..',
      '..CBBFFFFFFBBC..',
      '..CCBEEEEEEBCC..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'sapling',
    name: 'The Sapling',
    codename: 'Three words. Always the same.',
    tagline: 'I am Sapling.',
    color: '#65a30d',
    glow: '#bef264',
    palette: { A: '#365314', B: '#65a30d', C: '#84cc16', D: '#fde047', E: '#000000', F: '#a16207' },
    grid: check([
      '....CC..CC..CC..',
      '...CCCCCCCCCCC..',
      '....CCCCCCCC....',
      '.....AAAAAA.....',
      '....AFFFFFFA....',
      '...AFFFFFFFFA...',
      '..AFFEEFFEEFFA..',
      '..AFFFFFFFFFFA..',
      '..AFFFEEEEFFFA..',
      '..AFFFFFFFFFFA..',
      '..AAFFFFFFFFAA..',
      '..ABFBBBBBBFBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },

  /* ====================== DC-inspired ====================== */
  {
    key: 'night_watcher',
    name: 'The Night Watcher',
    codename: 'Notepad, grappling hook, vengeance',
    tagline: 'I&apos;m the on-call.',
    color: '#1f2937',
    glow: '#facc15',
    palette: { A: '#0c0a09', B: '#1f2937', C: '#facc15', D: '#dde7ee', E: '#000000' },
    grid: check([
      '..AA........AA..',
      '.AAAA......AAAA.',
      '.AAAAAAAAAAAAAA.',
      '..AAAAAAAAAAAA..',
      '..ABBBBBBBBBBA..',
      '..ABBDDDDDDBBA..',
      '..ABBDEEDDEEBBA.',
      '..ABBDDDDDDBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBEEEEBBBA..',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBBCCCCBBBA..',
      '..ABBBBBBBBBBA..',
      '...AAAAAAAAAA...',
      '....AAAAAAAA....',
    ]),
  },
  {
    key: 'last_son',
    name: 'The Last Son',
    codename: 'Faster than the build',
    tagline: 'Truth, justice, and clean diffs.',
    color: '#1d4ed8',
    glow: '#dc2626',
    palette: { A: '#1e3a8a', B: '#2563eb', C: '#fde68a', D: '#dc2626', E: '#1a1a1a', F: '#fbbf24' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ACCCCCCCCA...',
      '..ACCCCCCCCCCA..',
      '..ACCFFFFFFCCA..',
      '..ACFFEEFFEEFCA.',
      '..ACFFFFFFFFCCA.',
      '..ACFFFFFFFFCCA.',
      '..ACCFFDDDDFCCA.',
      '...ACCCCCCCCA...',
      '..ABBBBBBBBBBA..',
      '..ABBDFFFFDBBA..',
      '..ABBDFAAFDBBA..',
      '..ABBBDDDDBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'amazon',
    name: 'The Amazon',
    codename: 'Lasso of compile errors',
    tagline: 'Truth, in every PR.',
    color: '#b91c1c',
    glow: '#fde047',
    palette: { A: '#7f1d1d', B: '#b91c1c', C: '#0c4a6e', D: '#fde047', E: '#000000', F: '#f5d6b0' },
    grid: check([
      '......DDDD......',
      '.....DAADDD.....',
      '....CCCCCCCC....',
      '...CCCCCCCCCC...',
      '..CCFFFFFFFFCC..',
      '..CCFFEEFFEEFCC.',
      '..CCFFFFFFFFCCC.',
      '..CCFFFFFFFFCCC.',
      '..CCFFFBBBBFCCC.',
      '...CCCCCCCCCC...',
      '..ABBBBBBBBBBA..',
      '..ABBDDFFDDBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'speedster',
    name: 'The Speedster',
    codename: 'Ships in the time it takes to read this',
    tagline: 'PR open, PR merged.',
    color: '#dc2626',
    glow: '#facc15',
    palette: { A: '#7f1d1d', B: '#dc2626', C: '#fde047', D: '#fcd34d', E: '#000000', F: '#fed7aa' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBFFFFFFFBA..',
      '..ABBFEEBFEEFBA.',
      '..ABBFFFFFFFBBA.',
      '..ABBFFFFFFFBBA.',
      '..ABBFFEEEEFBBA.',
      '...ABBCCCCBBBA..',
      '..CABCDDDDCBBAC.',
      '..CABBBBBBBBBAC.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'tide_lord',
    name: 'The Tide Lord',
    codename: 'Steers the deep ones',
    tagline: 'Currents always change.',
    color: '#0c4a6e',
    glow: '#fde047',
    palette: { A: '#0c4a6e', B: '#0369a1', C: '#fde047', D: '#fed7aa', E: '#000000', F: '#65a30d' },
    grid: check([
      '................',
      '....CCCCCCCC....',
      '...CBBBBBBBBC...',
      '..CBBCCCCCCBBC..',
      '..CBDDDDDDDDBC..',
      '..CBDEEDDEEDBBC.',
      '..CBDDDDDDDDBBC.',
      '..CBDDDFFFFDBBC.',
      '..CBDDDDDDDDBBC.',
      '...CBBCCCCCBBC..',
      '..ABBBBBBBBBBA..',
      '..ABBCFFFFCBBA..',
      '..ABBCCCCCCBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'ring_bearer',
    name: 'The Ring Bearer',
    codename: 'Willpower compiled',
    tagline: 'No fear in the merge.',
    color: '#16a34a',
    glow: '#bbf7d0',
    palette: { A: '#052e16', B: '#16a34a', C: '#86efac', D: '#fde68a', E: '#000000', F: '#f5d6b0' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...AFFFFFFFFA...',
      '..AFFFFFFFFFFA..',
      '..ABBCCCCCCBBA..',
      '..ABCFEEFFEEFCBA',
      '..ABBCCCCCCCBBA.',
      '..AFFFFFFFFFFFA.',
      '..AFFFEEEEEEFFA.',
      '...AFFFFFFFFFA..',
      '..ABBBBBBBBBBA..',
      '..ABBBCCCCBBBA..',
      '..ABBCCAACCBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'jester',
    name: 'The Jester',
    codename: 'Why so deterministic?',
    tagline: 'Chaos is a ladder. Or a CI/CD pipeline.',
    color: '#7c2d12',
    glow: '#facc15',
    palette: { A: '#052e16', B: '#15803d', C: '#facc15', D: '#fef3c7', E: '#9a1a39', F: '#7c2d12' },
    grid: check([
      '...BBB....BBB...',
      '..BBBBBBBBBBBB..',
      '.BBBBBBBBBBBBBB.',
      '..BBBBBBBBBBBB..',
      '..DDDDDDDDDDDD..',
      '..DDFFDDDDFFDDD.',
      '..DDFFDDDDFFDDD.',
      '..DDDDDDDDDDDD..',
      '..DDDEEEEEEEDD..',
      '..DDEDEEEEEEDD..',
      '..DDDEEEEEEEDD..',
      '...DDDDDDDDD....',
      '..AABBBBBBBBAA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...AAAAAAAAAA...',
    ]),
  },
  {
    key: 'wild_card',
    name: 'The Wild Card',
    codename: 'Half pink, half blue, all chaos',
    tagline: 'Mr. J would be proud.',
    color: '#db2777',
    glow: '#7dd3fc',
    palette: { A: '#831843', B: '#db2777', C: '#0ea5e9', D: '#fde68a', E: '#000000', F: '#ffffff' },
    grid: check([
      '..CCC........BBB',
      '.CCCCCC....BBBBB',
      '.CCCCCCCBBBBBBB.',
      '..CCCCCCBBBBBB..',
      '..DDDDDDDDDDDD..',
      '..DDFEFDDDFEFDD.',
      '..DDDDDDDDDDDDD.',
      '..DDDDDFFFDDDD..',
      '..DDDEEEEEEEDD..',
      '..DDDFFEEFFFDD..',
      '..CBBBBBBBBBBBC.',
      '..CBFBBBBBBFBBC.',
      '..CBBBBBBBBBBBC.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'acrobat',
    name: 'The Acrobat',
    codename: 'No sidekick anymore',
    tagline: 'Lands the deploy like a backflip.',
    color: '#1e3a8a',
    glow: '#3b82f6',
    palette: { A: '#0c0a44', B: '#1e3a8a', C: '#3b82f6', D: '#f5d6b0', E: '#000000', F: '#fbbf24' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBDDDDDDBBA..',
      '..ACCCEEDDEECCA.',
      '..ACCCDDDDDDCCA.',
      '..ABDDDDDDDDDBA.',
      '..ABBDDFFFFDDBA.',
      '...ABBBBBBBBA...',
      '..ABCBBBBBBCBBA.',
      '..ABCBBBBBBCBBA.',
      '..ABBCCCCCCBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'boy_wonder',
    name: 'The Boy Wonder',
    codename: 'Junior dev, senior heart',
    tagline: 'Holy fast follow-ups.',
    color: '#dc2626',
    glow: '#facc15',
    palette: { A: '#7f1d1d', B: '#dc2626', C: '#15803d', D: '#facc15', E: '#000000', F: '#fef3c7' },
    grid: check([
      '................',
      '....DDDDDDDD....',
      '...DDDDDDDDDD...',
      '..DBBBBBBBBBBD..',
      '..DBFFFFFFFFBD..',
      '..DBEEBBBBEEBBD.',
      '..DBFFFFFFFFBBD.',
      '..DBFFFFFFFFBBD.',
      '..DBFFFBBBBFFBD.',
      '...DBFFFFFFBBD..',
      '..ABBCCCCCCBBA..',
      '..ABCCCFFCCCBBA.',
      '..ABCCCCCCCCBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'cat_burglar',
    name: 'The Cat Burglar',
    codename: 'Nine lives, nine PRs',
    tagline: 'Steals the spotlight, gracefully.',
    color: '#1c1917',
    glow: '#a855f7',
    palette: { A: '#0c0a09', B: '#1c1917', C: '#a855f7', D: '#fde68a', E: '#000000', F: '#fde047' },
    grid: check([
      '..BB........BB..',
      '..BBB......BBB..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBDDDDDDBBA..',
      '..ABBCEEBCEECBA.',
      '..ABDDDDDDDDDBA.',
      '..ABDDDFFFFDDBA.',
      '..ABBDDDDDDBBBA.',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBBFFFFBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'mogul',
    name: 'The Mogul',
    codename: 'Bald, brilliant, billionaire',
    tagline: 'Owns the board. And the bored.',
    color: '#14532d',
    glow: '#a3e635',
    palette: { A: '#052e16', B: '#14532d', C: '#84cc16', D: '#f5d6b0', E: '#000000', F: '#1c1917' },
    grid: check([
      '................',
      '.....DDDDDD.....',
      '....DDDDDDDD....',
      '...DDDDDDDDDD...',
      '..DDDDDDDDDDDD..',
      '..DDEEDDDDEEDD..',
      '..DDDDDDDDDDDD..',
      '..DDDDDFFDDDDD..',
      '..DDDDDDDDDDDD..',
      '..DDDFFFFFFDDD..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABCCCCCCCCBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },

  /* ====================== Anime-inspired ====================== */
  {
    key: 'fox_ninja',
    name: 'The Fox Ninja',
    codename: 'Loud, loyal, levels up',
    tagline: 'Believes it.',
    color: '#f97316',
    glow: '#fde047',
    palette: { A: '#7c2d12', B: '#f97316', C: '#fbbf24', D: '#f5d6b0', E: '#000000', F: '#1d4ed8' },
    grid: check([
      '..CCC......CCC..',
      '..CBC......CBC..',
      '..CCCCCCCCCCCC..',
      '..ACBBCCCCBBCCA.',
      '..AACCCCCCCCCAA.',
      '..AADDDDDDDDDAA.',
      '..ADDEEDDDEEDDA.',
      '..ADAADDDDAADDA.',
      '..ADDDDDDDDDDDA.',
      '..ADDDFFFFFDDDA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBFFFFFBBBA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'avenger_ninja',
    name: 'The Avenger Ninja',
    codename: 'Cool, complicated, deletes branches',
    tagline: 'Goes solo. Comes back.',
    color: '#1e1b4b',
    glow: '#a855f7',
    palette: { A: '#0c0a44', B: '#1e1b4b', C: '#a855f7', D: '#f5d6b0', E: '#dc2626', F: '#fde68a' },
    grid: check([
      '...AAAAAAAAAA...',
      '..AAAAAAAAAAAA..',
      '..ABBBBBBBBBBA..',
      '..ABBAACCAABBBA.',
      '..ADDDDDDDDDDDA.',
      '..ADEEDDDDEEDDA.',
      '..ADEDDDDDDEDDA.',
      '..ADDDDDDDDDDA..',
      '..ADDDFFFFFDDDA.',
      '..ADDDDDDDDDDDA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'copy_ninja',
    name: 'The Copy Ninja',
    codename: 'Reads the book mid-PR',
    tagline: 'Read 1,000 books. Still writing the 1,001st.',
    color: '#475569',
    glow: '#fde047',
    palette: { A: '#1e293b', B: '#475569', C: '#cbd5e1', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '..CCCCCCCCCCC...',
      '..CCBBCCCCBBCC..',
      '..CCCCCCCCCCCC..',
      '..CCDDDDDDDDCC..',
      '..CCDFEDDDDDDC..',
      '..CCDDDDDDDDDC..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBFFFFBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'shadow_ninja',
    name: 'The Shadow',
    codename: 'Smart, silent, sacrifices himself',
    tagline: 'Crow on shoulder. Bug in claw.',
    color: '#1c1917',
    glow: '#dc2626',
    palette: { A: '#0c0a09', B: '#1c1917', C: '#dc2626', D: '#f5d6b0', E: '#000000', F: '#7f1d1d' },
    grid: check([
      '..BBBBBBBBBBBB..',
      '.BBBBBBBBBBBBBB.',
      '.BBBBAAAAAABBBB.',
      '.BBBABBBBBBBBBB.',
      '..BBDDDDDDDDBB..',
      '..BBDCCBBCCDDB..',
      '..BBDCCBBCCDDB..',
      '..BBDDDDDDDDBB..',
      '..BBDDFFFFFDDB..',
      '..BBDDDDDDDDBB..',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'straw_hat',
    name: 'The Straw Hat',
    codename: 'Smiles like a sunrise',
    tagline: 'Pirate king of the prod queue.',
    color: '#fde047',
    glow: '#fbbf24',
    palette: { A: '#92400e', B: '#fde047', C: '#fbbf24', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '..BBBBBBBBBBBB..',
      '.BBBBBBBBBBBBBB.',
      'BBBBBBBBBBBBBBBB',
      '.BBFFFFFFFFFFBB.',
      '..BBBBBBBBBBBB..',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADDDEEEEEDDDA.',
      '..ADAAAAAAAAADA.',
      '..ABBBBBBBBBBBA.',
      '..ABBFFFFFFBBBA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'three_swords',
    name: 'The Three Swords',
    codename: 'Loses direction, finds the bug',
    tagline: 'Bandana over the bandana.',
    color: '#16a34a',
    glow: '#84cc16',
    palette: { A: '#14532d', B: '#16a34a', C: '#86efac', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '..BBBBBBBBBBBB..',
      '..BBFFFFFFFFBB..',
      '..BBFFEEFFEEFFB.',
      '..BBFFFFFFFFFBB.',
      '..ADDDDDDDDDDDA.',
      '..ADAADDDDAADDA.',
      '..ADEDDDDDDEDDA.',
      '..ADDDDDDDDDDA..',
      '..ADDDFFFFFDDDA.',
      '..ADDDDDDDDDDDA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'six_eyes',
    name: 'The Six Eyes',
    codename: 'Strongest. Honestly the strongest.',
    tagline: 'Saw it coming. From the beginning.',
    color: '#0ea5e9',
    glow: '#dbeafe',
    palette: { A: '#0c4a6e', B: '#0ea5e9', C: '#dbeafe', D: '#f5d6b0', E: '#000000', F: '#ffffff' },
    grid: check([
      '.CCCCCCCCCCCCCC.',
      '.CCCCFFFFFFCCCCC',
      '.CCCCCCCCCCCCCCC',
      '.CCCCCCCCCCCCCC.',
      '..AFFFFFFFFFFA..',
      '..ADDDDDDDDDDDA.',
      '..ABBBBBBBBBBBA.',
      '..ABCCCCCCCCCBA.',
      '..ABBBBBBBBBBBA.',
      '..ADDDFFFFFDDDA.',
      '..ADDDDDDDDDDDA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'captain',
    name: 'The Captain',
    codename: 'Humanity&apos;s strongest engineer',
    tagline: 'Tch. Filthy code.',
    color: '#1f2937',
    glow: '#cbd5e1',
    palette: { A: '#0c0a09', B: '#1f2937', C: '#94a3b8', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '..AAAAAAAAAAAA..',
      '.AAAAAAAAAAAAAA.',
      '.AABBBBBBBBBBBA.',
      '.AABBBBBBBBBBBA.',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDA..',
      '..ADDDFFFFFDDDA.',
      '..ADDDDDDDDDDA..',
      '..ABBBBBBBBBBBA.',
      '..ABCCCCCCCCCBA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'saiyan',
    name: 'The Saiyan',
    codename: 'Trains while the build runs',
    tagline: 'Going beyond.',
    color: '#1c1917',
    glow: '#facc15',
    palette: { A: '#0c0a09', B: '#1c1917', C: '#facc15', D: '#f5d6b0', E: '#000000', F: '#f97316' },
    grid: check([
      'BBB....BB....BBB',
      'BBBB..BBBB..BBBB',
      '.BBBBBBBBBBBBBB.',
      '..BBBBBBBBBBBB..',
      '..ABBBBBBBBBBA..',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADDDEEEEEDDDA.',
      '..ADDDDDDDDDDDA.',
      '..AFFFFFFFFFFFA.',
      '..AFFFFFFFFFFFA.',
      '..AFFFEEEEFFFA..',
      '..AFFFFFFFFFFA..',
      '...FFFFFFFFFF...',
      '....FFFFFFFF....',
    ]),
  },
  {
    key: 'prince_warrior',
    name: 'The Prince',
    codename: 'Pride before performance',
    tagline: 'It&apos;s over 9,000. PRs.',
    color: '#1e293b',
    glow: '#facc15',
    palette: { A: '#0c0a44', B: '#1e293b', C: '#facc15', D: '#f5d6b0', E: '#000000', F: '#3b82f6' },
    grid: check([
      'BBBBBBBBBBBBBBBB',
      '.BBBBBBBBBBBBBB.',
      '.BBBBBBBBBBBBBB.',
      '..BBBBBBBBBBBB..',
      '..ABBBBBBBBBBA..',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADDDEEEEEDDDA.',
      '..ADDDDDDDDDDDA.',
      '..AFFFFFFFFFFFA.',
      '..AFCCCCCCCCFFA.',
      '..AFFFFFFFFFFFA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },

  /* ====================== Fiction / fantasy / detective ====================== */
  {
    key: 'chosen',
    name: 'The Chosen',
    codename: 'Glasses, scar, owl',
    tagline: 'Always survives. Always merges.',
    color: '#7f1d1d',
    glow: '#fde047',
    palette: { A: '#1c1917', B: '#7c2d12', C: '#fde047', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '..AAAA...AAAAA..',
      '.AAAAAAAAAAAAA..',
      'AAAAAAAAAAAAAAA.',
      'AAAAAAAAAAAAAA..',
      '..ADDDDDDDDDDA..',
      '..ADFFEFEFFEDDA.',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDA..',
      '..ADDDFFFFFDDDA.',
      '..ADDFDDDDDDFDA.',
      '..ABBBBBBBBBBBA.',
      '..ABBCCCCCCBBBA.',
      '..ABBCBBBBCBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'brightest',
    name: 'The Brightest',
    codename: 'Knows the answer before you ask',
    tagline: 'It&apos;s leviOsa, not leviosA.',
    color: '#92400e',
    glow: '#fde68a',
    palette: { A: '#451a03', B: '#92400e', C: '#a16207', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '..BBBBBBBBBBBB..',
      '.BBBCCCBBBCCCBB.',
      'BBCCCCCCCCCCCCBB',
      'BBCCCCBBBBCCCCBB',
      '.BCDDDDDDDDDDDB.',
      '.BCDEEDDDDEEDDB.',
      '.BCDDDDDDDDDDB..',
      '.BCDDDFFFFDDDDB.',
      '..BBDDDDDDDDDB..',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
      '................',
    ]),
  },
  {
    key: 'loyal',
    name: 'The Loyal',
    codename: 'Best friend, best reviewer',
    tagline: 'Has the rat. And the back.',
    color: '#b45309',
    glow: '#fde68a',
    palette: { A: '#7c2d12', B: '#b45309', C: '#f59e0b', D: '#f5d6b0', E: '#000000', F: '#fde68a' },
    grid: check([
      '..BBBBBBBBBBBB..',
      '.BCCCCBBBBCCCCB.',
      'BBCCCCCBBBCCCCCB',
      'BBCCCCBBBBCCCCBB',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADFFFFFFFFFDA.',
      '..ADDDFFFFFDDDA.',
      '..ADDDDDDDDDDDA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'grey_wizard',
    name: 'The Grey Wizard',
    codename: 'Late. Precisely when intended.',
    tagline: 'You shall not… deploy on Friday.',
    color: '#374151',
    glow: '#fde68a',
    palette: { A: '#0f172a', B: '#374151', C: '#94a3b8', D: '#f5d6b0', E: '#000000', F: '#fde68a' },
    grid: check([
      '.......BB.......',
      '......BAAB......',
      '.....BAABAB.....',
      '....BAAAAAAB....',
      '...BAAAAAAAAB...',
      '..BBAAAAAAAABB..',
      '..BCCCCCCCCCCB..',
      '..BCCCEEFFEECCB.',
      '..BCFCCCCCCCCFB.',
      '..BCCFCCCCCCFCB.',
      '..BBCCCFFFFCCCB.',
      '..ABCCCCCCCCBBA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'returned_king',
    name: 'The Returned King',
    codename: 'Crown of branches, sword of merges',
    tagline: 'Today is not that day.',
    color: '#92400e',
    glow: '#fde047',
    palette: { A: '#451a03', B: '#92400e', C: '#fde047', D: '#f5d6b0', E: '#000000', F: '#1e293b' },
    grid: check([
      '....C..C..C.....',
      '....CCCCCCC.....',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADDDFFFFFDDDA.',
      '..ADDFFFFFFFDDA.',
      '..AFFFFFFFFFFFA.',
      '..AFFFFFFFFFFFA.',
      '..ABBBBBBBBBBBA.',
      '..ABBCCCCCCBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'bastard',
    name: 'The Bastard',
    codename: 'Knows nothing. Reviews everything.',
    tagline: 'Watches the wall and the diff.',
    color: '#1c1917',
    glow: '#94a3b8',
    palette: { A: '#0c0a09', B: '#1c1917', C: '#94a3b8', D: '#f5d6b0', E: '#000000', F: '#fde68a' },
    grid: check([
      '..AABAAAAAABAA..',
      '.AAAAAAAAAAAAAA.',
      'AAAAAAAAAAAAAAAA',
      '..ABBBBBBBBBBA..',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADDDFFFFFDDDA.',
      '..ADDDDDDDDDDDA.',
      '..ACCCCCCCCCCCA.',
      '..ACCCCCCCCCCCA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'imp',
    name: 'The Imp',
    codename: 'Drinks. Reads. Decides.',
    tagline: 'A mind needs books to think.',
    color: '#a16207',
    glow: '#fde68a',
    palette: { A: '#451a03', B: '#a16207', C: '#fde047', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '................',
      '....CCCCCCCC....',
      '...CCCBBBBCCCC..',
      '..CCBBBBBBBBCC..',
      '..CBDDDDDDDDBC..',
      '..CBDEEDDDDEDBC.',
      '..CBDDFDDDDDDBC.',
      '..CBDDDDDDDDDBC.',
      '..CBDDFFFFFDDBC.',
      '..CCBDDDDDDDBCC.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'detective',
    name: 'The Detective',
    codename: 'Eliminates the impossible',
    tagline: 'Whatever remains: ship it.',
    color: '#7f1d1d',
    glow: '#dde7ee',
    palette: { A: '#1c1917', B: '#7c2d12', C: '#dde7ee', D: '#f5d6b0', E: '#000000', F: '#94a3b8' },
    grid: check([
      '..BBBBBBBBBBBB..',
      '.BBBBBBBBBBBBBB.',
      'BBBBBBBBBBBBBBBB',
      'BBBFFFFFFFFFFBBB',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADDDFFFFFDDDA.',
      '..ADDFFFFFFFDDA.',
      '..ADDDDDDDDDDA..',
      '..ABBBBBBBBBBBA.',
      '..ACCCCCCCCCCCA.',
      '..ABBBBBBBBBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'pirate',
    name: 'The Pirate',
    codename: 'Why is the rum-time gone',
    tagline: 'Ships, in the most dramatic way.',
    color: '#7c2d12',
    glow: '#fde047',
    palette: { A: '#451a03', B: '#7c2d12', C: '#fde047', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '..CCCCCCCCCCCC..',
      '.CCCCCCCCCCCCCC.',
      'CCCCCCCCCCCCCCCC',
      '..AAAAAAAAAAAA..',
      '..ABBBBBBBBBBBA.',
      '..ADDDDDDDDDDA..',
      '..ADAEDDDDDEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADAAFFFFAAADA.',
      '..ADDFFEEEEFDDA.',
      '..ADDDDDDDDDDA..',
      '..ABBBBBBBBBBBA.',
      '..ABBFFBBFFBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
  {
    key: 'boogeyman',
    name: 'The Boogeyman',
    codename: 'You sent who? After me?',
    tagline: 'Quiet, focused, lethal.',
    color: '#0c0a09',
    glow: '#dc2626',
    palette: { A: '#0c0a09', B: '#1c1917', C: '#475569', D: '#f5d6b0', E: '#000000', F: '#dc2626' },
    grid: check([
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ADDDDDDDDDDA..',
      '..ADEEDDDDEEDDA.',
      '..ADDDDDDDDDDDA.',
      '..ADDDFFFFFDDDA.',
      '..ADDDDDDDDDDDA.',
      '..ABBBBBBBBBBA..',
      '..ACCCCCCCCCCCA.',
      '..AABBBBBBBBBAA.',
      '..ABBCCCCCCBBBA.',
      '..ABBBBBBBBBBA..',
      '...BBBBBBBBBB...',
      '....BBBBBBBB....',
    ]),
  },
]

const BY_KEY = new Map(CHARACTERS.map((c) => [c.key, c]))

export function getCharacter(key: string | null | undefined): Character | null {
  if (!key) return null
  return BY_KEY.get(key as CharacterKey) ?? null
}

export function isCharacterKey(key: string): key is CharacterKey {
  return BY_KEY.has(key as CharacterKey)
}
